name: Linux Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-wheel:
    name: "Build wheel"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Wheel
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            quay.io/pypa/manylinux2014_x86_64 \
            bash -exc '/opt/python/cp38-cp38/bin/python setup.py bdist_wheel && \
            yum install -y libcurl-devel && \
            /opt/python/cp38-cp38/bin/pip install ./dist/pyspider*'
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
