name: Linux Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-wheels:
    name: "Build wheel"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8   
    - name: Build Wheel
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl-dev
        pip wheel -w DEST_DIR .
